apiVersion: v1
kind: Service
metadata:
  name: pizz-ia-predict-service
spec:
  type: ClusterIP
  selector:
    app: pizz-ia-predict
  ports:
   - port: 80
     name: http
     targetPort: 5000
     protocol: TCP
