name: Kubernetes deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Render Deployment YAML
      uses: nowactions/envsubst@v1
      with:
        input: ./deployment.yaml.tmpl
        output: ./deployment.yaml
      env:
        GITHUB_SHA: ${{ github.sha }}

    - name: Deploy
      run: kubectl apply -f ./deployment.yaml